GET http://localhost:4000/produtos

###
GET http://localhost:4000/produtos/10

###
POST http://localhost:4000/produtos
Content-Type: application/json

{
    "nome": "iPhone 14 Pro Max",
    "descricao": "O iPhone 14 Pro Max é o mais recente smartphone da Apple, com uma tela de 6.7 polegadas e câmera tripla.",
    "marca": "Apple",
    "modelo": "iPhone 14 Pro Max",
    "imagem": "https://example.com/iphone14promax.jpg",
    "nota": 9.5,
    "videoReview": "https://example.com/review/iphone14promax",
    "tags": ["smartphone", "premium", "apple"],
    "precoBase": 1099.99,
    "precoPromocional": 999.99,
    "menorPreco": 949.99,
    "maiorPreco": 1199.99,
    "precoMedio": 1049.99,
    "especificacoes": "{ \"processador\": \"A16 Bionic\", \"memoria\": \"6GB RAM\", \"armazenamento\": \"128GB\" }"
}

###
DELETE http://localhost:4000/produtos/29