version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cod3r_postgres_db
    restart: always
    environment:
      POSTGRES_USER: cod3r
      POSTGRES_PASSWORD: cod3r
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
